Homework1
made-ml-in-prod-2021/panda1987ds pull request #2
Opened 2021-04-27 13:07 UTC by panda1987DS

За основы был взят пример "ml_project_example" 
Приложение исполняется из консоли.
Структура и примеры исполнения подробно описаны в файле README.

**Код разбит на следующие части:**
- чтение параметров работы
- чтение, разделение данных
- подготовка фичей (делается с помощью трансформеров, добавлен вручную написанный трансформер SquaringTransformer, который возводит фичу в квадрат)
- обучение модели, предсказание, вычисление метрик, сохранение модели на диск
- пайплайн, который вызывает все фунции по очереди, а также логирует процесс работы.

Все логи пишутся в файл train_model.log, а также в стандартный вывод. Сообщения выше worning также логируются в файл train_model.warm

**Предусмотрено три режима работы:**
1. Полный:
- считываются данные
- делятся на обучение и тест
- обрабатываются фичи
- обучается модель
- обученная модель сохраняется на диск
- выполняются предсказания
- считаются метрики на тестовой части данных, а также кросс- валидация на 10 вариантах разбития данных
- все метрики сохраняются в логи и файл метрик 

2. train: 
- считываются данные
- делятся на обучение и тест
- обрабатываются фичи
- обучается модель
- обученная модель сохраняется на диск

3. predict:

- считываются данные
- делятся на обучение и тест
- обрабатываются фичи
- считывается ранее сохраненная модель
- выполняются предсказания
- считаются метрики на тестовой части данных, а также кросс- валидация на 10 вариантах разбития данных
- все метрики сохраняются в логи и файл метрик
 

**_Самооценка:_**

-2) Назовите ветку homework1   1 балл **+**
-1) положите код в папку ml_project
0) В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла) **+**

1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов)
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)
- _**не до конца поняла данный пункт, можно ли считать файлы с метриками отчетами. Возможно 0 баллов**_  
2) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) **+**

3) использованы логгеры (2 балла) **+**

4) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов) **+**

5) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов)
- можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
- можно просто руками посоздавать данных, собственноручно написанными функциями
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается) 
**+, правда сторонние библиотеки не использовала, т.к. сами данные довольно простые**

6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)
**+**

7) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла) **+**

8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла) **+**

9) Обучите модель, запишите в readme как это предлагается (3 балла) **+**

10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла)  **+**

11) Используется hydra  (https://hydra.cc/docs/intro/) (3 балла - доп баллы) **-**

12) Настроен CI(прогон тестов, линтера) на основе github actions  (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome) **-**
13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы) **+**
**Итого 29 баллов**

2021-05-11 07:40 UTC, goodamigo commented
Добавьте в PR лейбл hw1

2021-05-11 07:47 UTC, goodamigo commented
Зачем в predict разбивать на train и test? Данная стадия должна просто выдавать результат по поданным на вход данным. На train и test следует разбивать при прогоне полного пайплайна и train части

2021-05-11 07:48 UTC, goodamigo commented
В структуре проекта указана папка с ноутбуками, ее не вижу

2021-05-11 08:02 UTC, goodamigo commented on ml_project/src/features/build_features.py
> +def build_transformer(params: FeatureParams) -> ColumnTransformer:
Хотелось бы побольше логов

2021-05-11 08:02 UTC, goodamigo commented on ml_project/tests/conftest.py
> +    return pd.DataFrame({**categorical_features, **numeric_features, **sq_features, **target_dict})
хотелось бы как-то похитрее генерить фичи, ближе к тем что реально в датасете про сердце есть

2021-05-12 19:49 UTC, panda1987DS commented on ml_project/src/features/build_features.py
> +def build_transformer(params: FeatureParams) -> ColumnTransformer:
Здравствуйте. Добавила побольше логов. Для этого немного переделала логирование, чтобы оно работало через конфигурационный файл

2021-05-12 19:55 UTC, panda1987DS commented on ml_project/tests/conftest.py
> +    return pd.DataFrame({**categorical_features, **numeric_features, **sq_features, **target_dict})
Не уверена, что получилось как-то хитрее, но расписала все фичи из датасета. Постаралась, чтобы данные получились похожие

2021-05-12 19:58 UTC, panda1987DS commented
> Зачем в predict разбивать на train и test? Данная стадия должна просто выдавать результат по поданным на вход данным. На train и test следует разбивать при прогоне полного пайплайна и train части

Исправила.

2021-05-12 19:58 UTC, panda1987DS commented
> В

Добавила ноутбук

2021-05-13 17:14 UTC, markovivl requested changes

2021-05-13 17:14 UTC, markovivl commented on ml_project/src/train_pipeline.py
> +
Очень перегруженная функция, более 50 строк. Хотелось бы подойти чуть более модульно, вынести в отдельные функции.

2021-05-13 20:55 UTC, goodamigo approved these changes
31 балл (1 доп балл за самооценку)

2021-05-13 20:55 UTC, goodamigo commented on ml_project/tests/test_fit_predict.py
> +def test_model_train(model_train, training_pipeline_params):
Как мне кажется немного странно тренировочную именно часть выносить в конфтест, но не критично

2021-05-14 06:35 UTC, panda1987DS commented on ml_project/src/train_pipeline.py
> +
Согласна, но поправить не успела)

2021-05-14 06:55 UTC, panda1987DS commented on ml_project/tests/test_fit_predict.py
> +def test_model_train(model_train, training_pipeline_params):
Глупо получилось. Я думала, модель пригодиться в других тестах.

Спасибо за ревью!!!

2021-05-14 07:05 UTC, merged